"""Phase 1 acceptance tests for forward-model Bayesian mechanism inference.

These are the runnable checkpoint defined by the XENON Leadership Directive: on a
synthetic network with known kinetic parameters, the posterior must recover the
ground truth within its credible interval, AND Bayesian model selection must rank
the true topology above decoy topologies. No leadership claim is valid until these
pass.
"""

from __future__ import annotations

import numpy as np
import pytest

from xenon.learning.forward_inference import (
    MechanismModel,
    Observation,
    metropolis_infer,
    model_selection,
    simulate_meanfield,
)


def _synthetic_data(true_rates, edges, species, seed=0, noise=0.02):
    """Generate observations from the true A->B->C network at several conditions."""
    rng = np.random.default_rng(seed)
    data = []
    initials = [
        {"A": 100.0, "B": 0.0, "C": 0.0},
        {"A": 50.0, "B": 20.0, "C": 0.0},
    ]
    times = [0.5, 1.0, 2.0, 4.0]
    for init in initials:
        for t in times:
            truth = simulate_meanfield(species, edges, true_rates, init, t)
            observed = {
                s: max(0.0, v + rng.normal(0.0, noise * 100.0)) for s, v in truth.items()
            }
            uncertainties = {s: noise * 100.0 for s in truth}
            data.append(Observation(initial=init, time=t, observed=observed, uncertainties=uncertainties))
    return data


SPECIES = ["A", "B", "C"]
TRUE_EDGES = [("A", "B"), ("B", "C")]
TRUE_RATES = [0.8, 0.3]  # k1, k2 (1/s)


class TestParameterRecovery:
    """The posterior over rate constants must contain the ground truth."""

    def test_recovers_true_rates_within_credible_interval(self):
        data = _synthetic_data(TRUE_RATES, TRUE_EDGES, SPECIES, seed=1)
        model = MechanismModel(species=SPECIES, edges=TRUE_EDGES)

        result = metropolis_infer(
            model, data, n_samples=4000, burn_in=1500, proposal_sigma=0.05, seed=7
        )

        ci = result.credible_interval(level=0.95)  # (n_params, 2)
        for p, true_k in enumerate(TRUE_RATES):
            lo, hi = ci[p]
            assert lo <= true_k <= hi, (
                f"rate {p}: true {true_k} not in 95% CI [{lo:.3f}, {hi:.3f}]"
            )

        # Posterior mean should be reasonably close to truth.
        post_mean = result.posterior_mean
        for p, true_k in enumerate(TRUE_RATES):
            assert abs(post_mean[p] - true_k) / true_k < 0.5
        # Sampler should be mixing, not stuck.
        assert 0.05 < result.acceptance_rate < 0.95


class TestModelSelection:
    """Bayesian model selection must rank the true topology highest."""

    def test_true_topology_ranked_above_decoys(self):
        data = _synthetic_data(TRUE_RATES, TRUE_EDGES, SPECIES, seed=2)

        true_model = MechanismModel(SPECIES, [("A", "B"), ("B", "C")])
        decoys = [
            MechanismModel(SPECIES, [("A", "C"), ("C", "B")]),  # wrong ordering
            MechanismModel(SPECIES, [("A", "B")]),  # missing edge
            MechanismModel(SPECIES, [("A", "B"), ("A", "C")]),  # wrong second edge
            MechanismModel(SPECIES, [("B", "A"), ("C", "B")]),  # reversed
        ]
        models = [true_model, *decoys]

        ranked = model_selection(models, data, n_samples=8000, seed=3)
        best_model, best_logZ, best_post = ranked[0]

        assert best_model.edges == true_model.edges, (
            f"true topology not ranked first; got {best_model.edges}"
        )
        # The true model should carry the dominant posterior mass.
        assert best_post > 0.5


class TestBayesianUpdaterUsesForwardModel:
    """The central-defect fix: with initial conditions, the updater scores
    mechanisms by forward-simulating them, so a mechanism whose dynamics match
    the data wins over one whose rates do not - regardless of stored state.
    """

    def _mechanism(self, name, k1, k2):
        from xenon.core.mechanism import BioMechanism, MolecularState, Transition

        mech = BioMechanism(name)
        for s in ("A", "B", "C"):
            mech.add_state(MolecularState(name=s, molecule=s))
        mech.add_transition(Transition(source="A", target="B", rate_constant=k1))
        mech.add_transition(Transition(source="B", target="C", rate_constant=k2))
        return mech

    def test_dynamically_correct_mechanism_wins(self):
        from xenon.learning.bayesian_updater import BayesianUpdater, ExperimentResult

        # Observation generated by the true dynamics (k1=0.8, k2=0.3) at t=2.
        truth = simulate_meanfield(
            SPECIES, TRUE_EDGES, TRUE_RATES, {"A": 100.0, "B": 0.0, "C": 0.0}, 2.0
        )
        exp = ExperimentResult(
            experiment_type="concentration",
            observations=truth,
            uncertainties={s: 2.0 for s in truth},
            initial_conditions={"A": 100.0, "B": 0.0, "C": 0.0},
            time=2.0,
        )

        correct = self._mechanism("correct", 0.8, 0.3)
        wrong = self._mechanism("wrong", 0.05, 5.0)
        correct.posterior = wrong.posterior = 0.5

        BayesianUpdater().update_mechanisms([correct, wrong], exp)
        assert correct.posterior > wrong.posterior
        assert correct.posterior > 0.9

    def test_legacy_path_without_initial_conditions_still_updates(self):
        from xenon.learning.bayesian_updater import BayesianUpdater, ExperimentResult

        mech = self._mechanism("m", 0.8, 0.3)
        mech.posterior = 0.5
        exp = ExperimentResult(
            experiment_type="concentration",
            observations={"A": 75.0, "B": 25.0},
            uncertainties={"A": 10.0, "B": 5.0},
        )  # no initial_conditions -> legacy fallback, must not error
        out = BayesianUpdater().update_mechanisms([mech], exp)
        assert len(out) == 1


def test_forward_model_is_deterministic_and_exact_for_decay():
    """A -> B with rate k: C_A(t) = A0 e^{-kt}, C_B(t) = A0 (1 - e^{-kt})."""
    out = simulate_meanfield(["A", "B"], [("A", "B")], [0.7], {"A": 100.0, "B": 0.0}, 1.3)
    expected_a = 100.0 * np.exp(-0.7 * 1.3)
    assert out["A"] == pytest.approx(expected_a, rel=1e-6)
    assert out["B"] == pytest.approx(100.0 - expected_a, rel=1e-6)
